
namespace Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Admin.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string accountspayableap {
                                get {
                                    return ResourceManager.GetString("accountspayableap", resourceCulture);
                                }
                            }
                            
public static string accountsreceivablearcollections {
                                get {
                                    return ResourceManager.GetString("accountsreceivablearcollections", resourceCulture);
                                }
                            }
                            
public static string @action {
                                get {
                                    return ResourceManager.GetString("action", resourceCulture);
                                }
                            }
                            
public static string addcheckin {
                                get {
                                    return ResourceManager.GetString("addcheckin", resourceCulture);
                                }
                            }
                            
public static string addcheckout {
                                get {
                                    return ResourceManager.GetString("addcheckout", resourceCulture);
                                }
                            }
                            
public static string addedinvoice {
                                get {
                                    return ResourceManager.GetString("addedinvoice", resourceCulture);
                                }
                            }
                            
public static string addfeedback {
                                get {
                                    return ResourceManager.GetString("addfeedback", resourceCulture);
                                }
                            }
                            
public static string addguest {
                                get {
                                    return ResourceManager.GetString("addguest", resourceCulture);
                                }
                            }
                            
public static string addhousekeeping {
                                get {
                                    return ResourceManager.GetString("addhousekeeping", resourceCulture);
                                }
                            }
                            
public static string addinvoice {
                                get {
                                    return ResourceManager.GetString("addinvoice", resourceCulture);
                                }
                            }
                            
public static string addpayment {
                                get {
                                    return ResourceManager.GetString("addpayment", resourceCulture);
                                }
                            }
                            
public static string addreceptionist {
                                get {
                                    return ResourceManager.GetString("addreceptionist", resourceCulture);
                                }
                            }
                            
public static string addreservation {
                                get {
                                    return ResourceManager.GetString("addreservation", resourceCulture);
                                }
                            }
                            
public static string address {
                                get {
                                    return ResourceManager.GetString("address", resourceCulture);
                                }
                            }
                            
public static string addroom {
                                get {
                                    return ResourceManager.GetString("addroom", resourceCulture);
                                }
                            }
                            
public static string agencypartnermanagement {
                                get {
                                    return ResourceManager.GetString("agencypartnermanagement", resourceCulture);
                                }
                            }
                            
public static string alerttemplates {
                                get {
                                    return ResourceManager.GetString("alerttemplates", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertcarboncopyto {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertcarboncopyto", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertcontent {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertcontent", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertcopyto {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertcopyto", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alertsubject {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alertsubject", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_alerttype {
                                get {
                                    return ResourceManager.GetString("alerttemplates_alerttype", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_entityaction {
                                get {
                                    return ResourceManager.GetString("alerttemplates_entityaction", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_entityname {
                                get {
                                    return ResourceManager.GetString("alerttemplates_entityname", resourceCulture);
                                }
                            }
                            
public static string alerttemplates_sendasbatch {
                                get {
                                    return ResourceManager.GetString("alerttemplates_sendasbatch", resourceCulture);
                                }
                            }
                            
public static string alerttemplateslist {
                                get {
                                    return ResourceManager.GetString("alerttemplateslist", resourceCulture);
                                }
                            }
                            
public static string appadmin {
                                get {
                                    return ResourceManager.GetString("appadmin", resourceCulture);
                                }
                            }
                            
public static string apply {
                                get {
                                    return ResourceManager.GetString("apply", resourceCulture);
                                }
                            }
                            
public static string approveddetailinvoice {
                                get {
                                    return ResourceManager.GetString("approveddetailinvoice", resourceCulture);
                                }
                            }
                            
public static string authenticate {
                                get {
                                    return ResourceManager.GetString("authenticate", resourceCulture);
                                }
                            }
                            
public static string back {
                                get {
                                    return ResourceManager.GetString("back", resourceCulture);
                                }
                            }
                            
public static string beveragemanagementbarprograms {
                                get {
                                    return ResourceManager.GetString("beveragemanagementbarprograms", resourceCulture);
                                }
                            }
                            
public static string bookingconversionleadsmanagement {
                                get {
                                    return ResourceManager.GetString("bookingconversionleadsmanagement", resourceCulture);
                                }
                            }
                            
public static string campaignplanningexecution {
                                get {
                                    return ResourceManager.GetString("campaignplanningexecution", resourceCulture);
                                }
                            }
                            
public static string cancel {
                                get {
                                    return ResourceManager.GetString("cancel", resourceCulture);
                                }
                            }
                            
public static string changepassword {
                                get {
                                    return ResourceManager.GetString("changepassword", resourceCulture);
                                }
                            }
                            
public static string checkerdetailinvoice {
                                get {
                                    return ResourceManager.GetString("checkerdetailinvoice", resourceCulture);
                                }
                            }
                            
public static string checkin {
                                get {
                                    return ResourceManager.GetString("checkin", resourceCulture);
                                }
                            }
                            
public static string checkinidentityverification {
                                get {
                                    return ResourceManager.GetString("checkinidentityverification", resourceCulture);
                                }
                            }
                            
public static string checkin_checkindate {
                                get {
                                    return ResourceManager.GetString("checkin_checkindate", resourceCulture);
                                }
                            }
                            
public static string checkin_checkinno {
                                get {
                                    return ResourceManager.GetString("checkin_checkinno", resourceCulture);
                                }
                            }
                            
public static string checkin_checkintime {
                                get {
                                    return ResourceManager.GetString("checkin_checkintime", resourceCulture);
                                }
                            }
                            
public static string checkin_depositamount {
                                get {
                                    return ResourceManager.GetString("checkin_depositamount", resourceCulture);
                                }
                            }
                            
public static string checkin_guestno {
                                get {
                                    return ResourceManager.GetString("checkin_guestno", resourceCulture);
                                }
                            }
                            
public static string checkin_roomno {
                                get {
                                    return ResourceManager.GetString("checkin_roomno", resourceCulture);
                                }
                            }
                            
public static string checkin_status {
                                get {
                                    return ResourceManager.GetString("checkin_status", resourceCulture);
                                }
                            }
                            
public static string checkinlist {
                                get {
                                    return ResourceManager.GetString("checkinlist", resourceCulture);
                                }
                            }
                            
public static string checkout {
                                get {
                                    return ResourceManager.GetString("checkout", resourceCulture);
                                }
                            }
                            
public static string checkoutdepartureprocessing {
                                get {
                                    return ResourceManager.GetString("checkoutdepartureprocessing", resourceCulture);
                                }
                            }
                            
public static string checkout_checkoutdate {
                                get {
                                    return ResourceManager.GetString("checkout_checkoutdate", resourceCulture);
                                }
                            }
                            
public static string checkout_checkoutno {
                                get {
                                    return ResourceManager.GetString("checkout_checkoutno", resourceCulture);
                                }
                            }
                            
public static string checkout_checkouttime {
                                get {
                                    return ResourceManager.GetString("checkout_checkouttime", resourceCulture);
                                }
                            }
                            
public static string checkout_finalbill {
                                get {
                                    return ResourceManager.GetString("checkout_finalbill", resourceCulture);
                                }
                            }
                            
public static string checkout_guestno {
                                get {
                                    return ResourceManager.GetString("checkout_guestno", resourceCulture);
                                }
                            }
                            
public static string checkout_roomno {
                                get {
                                    return ResourceManager.GetString("checkout_roomno", resourceCulture);
                                }
                            }
                            
public static string checkout_status {
                                get {
                                    return ResourceManager.GetString("checkout_status", resourceCulture);
                                }
                            }
                            
public static string checkoutlist {
                                get {
                                    return ResourceManager.GetString("checkoutlist", resourceCulture);
                                }
                            }
                            
public static string cleaningscheduling {
                                get {
                                    return ResourceManager.GetString("cleaningscheduling", resourceCulture);
                                }
                            }
                            
public static string client {
                                get {
                                    return ResourceManager.GetString("client", resourceCulture);
                                }
                            }
                            
public static string clone {
                                get {
                                    return ResourceManager.GetString("clone", resourceCulture);
                                }
                            }
                            
public static string contentbrandmanagement {
                                get {
                                    return ResourceManager.GetString("contentbrandmanagement", resourceCulture);
                                }
                            }
                            
public static string createalerttemplates {
                                get {
                                    return ResourceManager.GetString("createalerttemplates", resourceCulture);
                                }
                            }
                            
public static string createhotelowners {
                                get {
                                    return ResourceManager.GetString("createhotelowners", resourceCulture);
                                }
                            }
                            
public static string createmaillog {
                                get {
                                    return ResourceManager.GetString("createmaillog", resourceCulture);
                                }
                            }
                            
public static string demandforecasting {
                                get {
                                    return ResourceManager.GetString("demandforecasting", resourceCulture);
                                }
                            }
                            
public static string detail {
                                get {
                                    return ResourceManager.GetString("detail", resourceCulture);
                                }
                            }
                            
public static string detailalerttemplates {
                                get {
                                    return ResourceManager.GetString("detailalerttemplates", resourceCulture);
                                }
                            }
                            
public static string detailcheckin {
                                get {
                                    return ResourceManager.GetString("detailcheckin", resourceCulture);
                                }
                            }
                            
public static string detailcheckout {
                                get {
                                    return ResourceManager.GetString("detailcheckout", resourceCulture);
                                }
                            }
                            
public static string detailfeedback {
                                get {
                                    return ResourceManager.GetString("detailfeedback", resourceCulture);
                                }
                            }
                            
public static string detailguest {
                                get {
                                    return ResourceManager.GetString("detailguest", resourceCulture);
                                }
                            }
                            
public static string detailhousekeeping {
                                get {
                                    return ResourceManager.GetString("detailhousekeeping", resourceCulture);
                                }
                            }
                            
public static string detailmaillog {
                                get {
                                    return ResourceManager.GetString("detailmaillog", resourceCulture);
                                }
                            }
                            
public static string detailpayment {
                                get {
                                    return ResourceManager.GetString("detailpayment", resourceCulture);
                                }
                            }
                            
public static string detailreceptionist {
                                get {
                                    return ResourceManager.GetString("detailreceptionist", resourceCulture);
                                }
                            }
                            
public static string detailreservation {
                                get {
                                    return ResourceManager.GetString("detailreservation", resourceCulture);
                                }
                            }
                            
public static string detailroom {
                                get {
                                    return ResourceManager.GetString("detailroom", resourceCulture);
                                }
                            }
                            
public static string distributionsetupotasgdsdirect {
                                get {
                                    return ResourceManager.GetString("distributionsetupotasgdsdirect", resourceCulture);
                                }
                            }
                            
public static string download {
                                get {
                                    return ResourceManager.GetString("download", resourceCulture);
                                }
                            }
                            
public static string emergencyrepairsoncallresponse {
                                get {
                                    return ResourceManager.GetString("emergencyrepairsoncallresponse", resourceCulture);
                                }
                            }
                            
public static string employee {
                                get {
                                    return ResourceManager.GetString("employee", resourceCulture);
                                }
                            }
                            
public static string equipmentinventorymanagement {
                                get {
                                    return ResourceManager.GetString("equipmentinventorymanagement", resourceCulture);
                                }
                            }
                            
public static string eventcloseoutbilling {
                                get {
                                    return ResourceManager.GetString("eventcloseoutbilling", resourceCulture);
                                }
                            }
                            
public static string eventexecutionguestexperience {
                                get {
                                    return ResourceManager.GetString("eventexecutionguestexperience", resourceCulture);
                                }
                            }
                            
public static string eventplanningstaffing {
                                get {
                                    return ResourceManager.GetString("eventplanningstaffing", resourceCulture);
                                }
                            }
                            
public static string eventsalesproposaldevelopment {
                                get {
                                    return ResourceManager.GetString("eventsalesproposaldevelopment", resourceCulture);
                                }
                            }
                            
public static string feedback {
                                get {
                                    return ResourceManager.GetString("feedback", resourceCulture);
                                }
                            }
                            
public static string feedback_feedbackno {
                                get {
                                    return ResourceManager.GetString("feedback_feedbackno", resourceCulture);
                                }
                            }
                            
public static string feedback_guestno {
                                get {
                                    return ResourceManager.GetString("feedback_guestno", resourceCulture);
                                }
                            }
                            
public static string feedback_roomrating {
                                get {
                                    return ResourceManager.GetString("feedback_roomrating", resourceCulture);
                                }
                            }
                            
public static string feedback_staffrating {
                                get {
                                    return ResourceManager.GetString("feedback_staffrating", resourceCulture);
                                }
                            }
                            
public static string feedbacklist {
                                get {
                                    return ResourceManager.GetString("feedbacklist", resourceCulture);
                                }
                            }
                            
public static string financialreportingbudgeting {
                                get {
                                    return ResourceManager.GetString("financialreportingbudgeting", resourceCulture);
                                }
                            }
                            
public static string foodsafetyhygienecompliance {
                                get {
                                    return ResourceManager.GetString("foodsafetyhygienecompliance", resourceCulture);
                                }
                            }
                            
public static string forgotpasswordcommon {
                                get {
                                    return ResourceManager.GetString("forgotpasswordcommon", resourceCulture);
                                }
                            }
                            
public static string @from {
                                get {
                                    return ResourceManager.GetString("from", resourceCulture);
                                }
                            }
                            
public static string guest {
                                get {
                                    return ResourceManager.GetString("guest", resourceCulture);
                                }
                            }
                            
public static string guest_addressline1 {
                                get {
                                    return ResourceManager.GetString("guest_addressline1", resourceCulture);
                                }
                            }
                            
public static string guest_city {
                                get {
                                    return ResourceManager.GetString("guest_city", resourceCulture);
                                }
                            }
                            
public static string guest_country {
                                get {
                                    return ResourceManager.GetString("guest_country", resourceCulture);
                                }
                            }
                            
public static string guest_email {
                                get {
                                    return ResourceManager.GetString("guest_email", resourceCulture);
                                }
                            }
                            
public static string guest_gender {
                                get {
                                    return ResourceManager.GetString("guest_gender", resourceCulture);
                                }
                            }
                            
public static string guest_guestname {
                                get {
                                    return ResourceManager.GetString("guest_guestname", resourceCulture);
                                }
                            }
                            
public static string guest_guestno {
                                get {
                                    return ResourceManager.GetString("guest_guestno", resourceCulture);
                                }
                            }
                            
public static string guest_idproof {
                                get {
                                    return ResourceManager.GetString("guest_idproof", resourceCulture);
                                }
                            }
                            
public static string guest_phonenumber {
                                get {
                                    return ResourceManager.GetString("guest_phonenumber", resourceCulture);
                                }
                            }
                            
public static string guest_statename {
                                get {
                                    return ResourceManager.GetString("guest_statename", resourceCulture);
                                }
                            }
                            
public static string guestbillingposreconciliation {
                                get {
                                    return ResourceManager.GetString("guestbillingposreconciliation", resourceCulture);
                                }
                            }
                            
public static string guestcheckoutandbilling {
                                get {
                                    return ResourceManager.GetString("guestcheckoutandbilling", resourceCulture);
                                }
                            }
                            
public static string guestfeedbackservicerecovery {
                                get {
                                    return ResourceManager.GetString("guestfeedbackservicerecovery", resourceCulture);
                                }
                            }
                            
public static string guestlist {
                                get {
                                    return ResourceManager.GetString("guestlist", resourceCulture);
                                }
                            }
                            
public static string guestreservationandcheckin {
                                get {
                                    return ResourceManager.GetString("guestreservationandcheckin", resourceCulture);
                                }
                            }
                            
public static string guestsupportduringstay {
                                get {
                                    return ResourceManager.GetString("guestsupportduringstay", resourceCulture);
                                }
                            }
                            
public static string hotelownersadmin {
                                get {
                                    return ResourceManager.GetString("hotelownersadmin", resourceCulture);
                                }
                            }
                            
public static string housekeeping {
                                get {
                                    return ResourceManager.GetString("housekeeping", resourceCulture);
                                }
                            }
                            
public static string housekeeping_cleaningdate {
                                get {
                                    return ResourceManager.GetString("housekeeping_cleaningdate", resourceCulture);
                                }
                            }
                            
public static string housekeeping_cleaningstatus {
                                get {
                                    return ResourceManager.GetString("housekeeping_cleaningstatus", resourceCulture);
                                }
                            }
                            
public static string housekeeping_housekeepingno {
                                get {
                                    return ResourceManager.GetString("housekeeping_housekeepingno", resourceCulture);
                                }
                            }
                            
public static string housekeeping_remark {
                                get {
                                    return ResourceManager.GetString("housekeeping_remark", resourceCulture);
                                }
                            }
                            
public static string housekeeping_roomno {
                                get {
                                    return ResourceManager.GetString("housekeeping_roomno", resourceCulture);
                                }
                            }
                            
public static string housekeeping_supervisor {
                                get {
                                    return ResourceManager.GetString("housekeeping_supervisor", resourceCulture);
                                }
                            }
                            
public static string housekeepinglist {
                                get {
                                    return ResourceManager.GetString("housekeepinglist", resourceCulture);
                                }
                            }
                            
public static string incidentmanagementreporting {
                                get {
                                    return ResourceManager.GetString("incidentmanagementreporting", resourceCulture);
                                }
                            }
                            
public static string @index {
                                get {
                                    return ResourceManager.GetString("index", resourceCulture);
                                }
                            }
                            
public static string inspectionsauditreadiness {
                                get {
                                    return ResourceManager.GetString("inspectionsauditreadiness", resourceCulture);
                                }
                            }
                            
public static string inspectionsqualitycontrol {
                                get {
                                    return ResourceManager.GetString("inspectionsqualitycontrol", resourceCulture);
                                }
                            }
                            
public static string inventoryoverbookingcontrols {
                                get {
                                    return ResourceManager.GetString("inventoryoverbookingcontrols", resourceCulture);
                                }
                            }
                            
public static string inventoryplanning {
                                get {
                                    return ResourceManager.GetString("inventoryplanning", resourceCulture);
                                }
                            }
                            
public static string invoice {
                                get {
                                    return ResourceManager.GetString("invoice", resourceCulture);
                                }
                            }
                            
public static string invoice_bookingnumber {
                                get {
                                    return ResourceManager.GetString("invoice_bookingnumber", resourceCulture);
                                }
                            }
                            
public static string invoice_guestno {
                                get {
                                    return ResourceManager.GetString("invoice_guestno", resourceCulture);
                                }
                            }
                            
public static string invoice_invoicedate {
                                get {
                                    return ResourceManager.GetString("invoice_invoicedate", resourceCulture);
                                }
                            }
                            
public static string invoice_invoicenumber {
                                get {
                                    return ResourceManager.GetString("invoice_invoicenumber", resourceCulture);
                                }
                            }
                            
public static string invoice_roomcharges {
                                get {
                                    return ResourceManager.GetString("invoice_roomcharges", resourceCulture);
                                }
                            }
                            
public static string invoice_taxdiscount {
                                get {
                                    return ResourceManager.GetString("invoice_taxdiscount", resourceCulture);
                                }
                            }
                            
public static string invoice_totalamount {
                                get {
                                    return ResourceManager.GetString("invoice_totalamount", resourceCulture);
                                }
                            }
                            
public static string invoice_verifiedstatus {
                                get {
                                    return ResourceManager.GetString("invoice_verifiedstatus", resourceCulture);
                                }
                            }
                            
public static string invoiceforreview {
                                get {
                                    return ResourceManager.GetString("invoiceforreview", resourceCulture);
                                }
                            }
                            
public static string invoicelist {
                                get {
                                    return ResourceManager.GetString("invoicelist", resourceCulture);
                                }
                            }
                            
public static string kitchenserviceexecution {
                                get {
                                    return ResourceManager.GetString("kitchenserviceexecution", resourceCulture);
                                }
                            }
                            
public static string laundrylinenmanagement {
                                get {
                                    return ResourceManager.GetString("laundrylinenmanagement", resourceCulture);
                                }
                            }
                            
public static string listofuserprofiles {
                                get {
                                    return ResourceManager.GetString("listofuserprofiles", resourceCulture);
                                }
                            }
                            
public static string login {
                                get {
                                    return ResourceManager.GetString("login", resourceCulture);
                                }
                            }
                            
public static string logininformation {
                                get {
                                    return ResourceManager.GetString("logininformation", resourceCulture);
                                }
                            }
                            
public static string logout {
                                get {
                                    return ResourceManager.GetString("logout", resourceCulture);
                                }
                            }
                            
public static string lookups {
                                get {
                                    return ResourceManager.GetString("lookups", resourceCulture);
                                }
                            }
                            
public static string loyaltyprogramsretention {
                                get {
                                    return ResourceManager.GetString("loyaltyprogramsretention", resourceCulture);
                                }
                            }
                            
public static string maillogs {
                                get {
                                    return ResourceManager.GetString("maillogs", resourceCulture);
                                }
                            }
                            
public static string maillogs_entityid {
                                get {
                                    return ResourceManager.GetString("maillogs_entityid", resourceCulture);
                                }
                            }
                            
public static string maillogs_entityname {
                                get {
                                    return ResourceManager.GetString("maillogs_entityname", resourceCulture);
                                }
                            }
                            
public static string maillogs_issent {
                                get {
                                    return ResourceManager.GetString("maillogs_issent", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailbody {
                                get {
                                    return ResourceManager.GetString("maillogs_mailbody", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailfor {
                                get {
                                    return ResourceManager.GetString("maillogs_mailfor", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailsubject {
                                get {
                                    return ResourceManager.GetString("maillogs_mailsubject", resourceCulture);
                                }
                            }
                            
public static string maillogs_mailto {
                                get {
                                    return ResourceManager.GetString("maillogs_mailto", resourceCulture);
                                }
                            }
                            
public static string maillogslist {
                                get {
                                    return ResourceManager.GetString("maillogslist", resourceCulture);
                                }
                            }
                            
public static string makerdetailinvoice {
                                get {
                                    return ResourceManager.GetString("makerdetailinvoice", resourceCulture);
                                }
                            }
                            
public static string managehotelowners {
                                get {
                                    return ResourceManager.GetString("managehotelowners", resourceCulture);
                                }
                            }
                            
public static string manager {
                                get {
                                    return ResourceManager.GetString("manager", resourceCulture);
                                }
                            }
                            
public static string manageroleauthorization {
                                get {
                                    return ResourceManager.GetString("manageroleauthorization", resourceCulture);
                                }
                            }
                            
public static string manageusers {
                                get {
                                    return ResourceManager.GetString("manageusers", resourceCulture);
                                }
                            }
                            
public static string marketsegmentationtargeting {
                                get {
                                    return ResourceManager.GetString("marketsegmentationtargeting", resourceCulture);
                                }
                            }
                            
public static string menuplanningpricing {
                                get {
                                    return ResourceManager.GetString("menuplanningpricing", resourceCulture);
                                }
                            }
                            
public static string payment {
                                get {
                                    return ResourceManager.GetString("payment", resourceCulture);
                                }
                            }
                            
public static string payment_guestno {
                                get {
                                    return ResourceManager.GetString("payment_guestno", resourceCulture);
                                }
                            }
                            
public static string payment_invoiceno {
                                get {
                                    return ResourceManager.GetString("payment_invoiceno", resourceCulture);
                                }
                            }
                            
public static string payment_noofdays {
                                get {
                                    return ResourceManager.GetString("payment_noofdays", resourceCulture);
                                }
                            }
                            
public static string payment_paymentdate {
                                get {
                                    return ResourceManager.GetString("payment_paymentdate", resourceCulture);
                                }
                            }
                            
public static string payment_paymentmethod {
                                get {
                                    return ResourceManager.GetString("payment_paymentmethod", resourceCulture);
                                }
                            }
                            
public static string payment_paymentno {
                                get {
                                    return ResourceManager.GetString("payment_paymentno", resourceCulture);
                                }
                            }
                            
public static string payment_paymentstatus {
                                get {
                                    return ResourceManager.GetString("payment_paymentstatus", resourceCulture);
                                }
                            }
                            
public static string payment_roomrent {
                                get {
                                    return ResourceManager.GetString("payment_roomrent", resourceCulture);
                                }
                            }
                            
public static string payment_totalamount {
                                get {
                                    return ResourceManager.GetString("payment_totalamount", resourceCulture);
                                }
                            }
                            
public static string payment_transactionno {
                                get {
                                    return ResourceManager.GetString("payment_transactionno", resourceCulture);
                                }
                            }
                            
public static string paymentlist {
                                get {
                                    return ResourceManager.GetString("paymentlist", resourceCulture);
                                }
                            }
                            
public static string payrolllaborcosttracking {
                                get {
                                    return ResourceManager.GetString("payrolllaborcosttracking", resourceCulture);
                                }
                            }
                            
public static string performancecompliancemonitoring {
                                get {
                                    return ResourceManager.GetString("performancecompliancemonitoring", resourceCulture);
                                }
                            }
                            
public static string platformadmin {
                                get {
                                    return ResourceManager.GetString("platformadmin", resourceCulture);
                                }
                            }
                            
public static string preventivemaintenance {
                                get {
                                    return ResourceManager.GetString("preventivemaintenance", resourceCulture);
                                }
                            }
                            
public static string preventivemaintenancecoordination {
                                get {
                                    return ResourceManager.GetString("preventivemaintenancecoordination", resourceCulture);
                                }
                            }
                            
public static string @print {
                                get {
                                    return ResourceManager.GetString("print", resourceCulture);
                                }
                            }
                            
public static string procurementsuppliermanagement {
                                get {
                                    return ResourceManager.GetString("procurementsuppliermanagement", resourceCulture);
                                }
                            }
                            
public static string promotionspackages {
                                get {
                                    return ResourceManager.GetString("promotionspackages", resourceCulture);
                                }
                            }
                            
public static string providertenantdisplayname {
                                get {
                                    return ResourceManager.GetString("providertenantdisplayname", resourceCulture);
                                }
                            }
                            
public static string purchasingvendorquotes {
                                get {
                                    return ResourceManager.GetString("purchasingvendorquotes", resourceCulture);
                                }
                            }
                            
public static string ratesettingupdates {
                                get {
                                    return ResourceManager.GetString("ratesettingupdates", resourceCulture);
                                }
                            }
                            
public static string receivingstockallocation {
                                get {
                                    return ResourceManager.GetString("receivingstockallocation", resourceCulture);
                                }
                            }
                            
public static string receptionist {
                                get {
                                    return ResourceManager.GetString("receptionist", resourceCulture);
                                }
                            }
                            
public static string receptionist_email {
                                get {
                                    return ResourceManager.GetString("receptionist_email", resourceCulture);
                                }
                            }
                            
public static string receptionist_employeename {
                                get {
                                    return ResourceManager.GetString("receptionist_employeename", resourceCulture);
                                }
                            }
                            
public static string receptionist_employeeno {
                                get {
                                    return ResourceManager.GetString("receptionist_employeeno", resourceCulture);
                                }
                            }
                            
public static string receptionist_experience {
                                get {
                                    return ResourceManager.GetString("receptionist_experience", resourceCulture);
                                }
                            }
                            
public static string receptionist_phonenumber {
                                get {
                                    return ResourceManager.GetString("receptionist_phonenumber", resourceCulture);
                                }
                            }
                            
public static string receptionist_salary {
                                get {
                                    return ResourceManager.GetString("receptionist_salary", resourceCulture);
                                }
                            }
                            
public static string receptionist_shift {
                                get {
                                    return ResourceManager.GetString("receptionist_shift", resourceCulture);
                                }
                            }
                            
public static string receptionistlist {
                                get {
                                    return ResourceManager.GetString("receptionistlist", resourceCulture);
                                }
                            }
                            
public static string recruitmentonboarding {
                                get {
                                    return ResourceManager.GetString("recruitmentonboarding", resourceCulture);
                                }
                            }
                            
public static string registerprofile {
                                get {
                                    return ResourceManager.GetString("registerprofile", resourceCulture);
                                }
                            }
                            
public static string regulatorycompliancemonitoring {
                                get {
                                    return ResourceManager.GetString("regulatorycompliancemonitoring", resourceCulture);
                                }
                            }
                            
public static string removealerttemplates {
                                get {
                                    return ResourceManager.GetString("removealerttemplates", resourceCulture);
                                }
                            }
                            
public static string removecheckin {
                                get {
                                    return ResourceManager.GetString("removecheckin", resourceCulture);
                                }
                            }
                            
public static string removecheckout {
                                get {
                                    return ResourceManager.GetString("removecheckout", resourceCulture);
                                }
                            }
                            
public static string removefeedback {
                                get {
                                    return ResourceManager.GetString("removefeedback", resourceCulture);
                                }
                            }
                            
public static string removeguest {
                                get {
                                    return ResourceManager.GetString("removeguest", resourceCulture);
                                }
                            }
                            
public static string removehotelowners {
                                get {
                                    return ResourceManager.GetString("removehotelowners", resourceCulture);
                                }
                            }
                            
public static string removehousekeeping {
                                get {
                                    return ResourceManager.GetString("removehousekeeping", resourceCulture);
                                }
                            }
                            
public static string removeinvoice {
                                get {
                                    return ResourceManager.GetString("removeinvoice", resourceCulture);
                                }
                            }
                            
public static string removemaillog {
                                get {
                                    return ResourceManager.GetString("removemaillog", resourceCulture);
                                }
                            }
                            
public static string removepayment {
                                get {
                                    return ResourceManager.GetString("removepayment", resourceCulture);
                                }
                            }
                            
public static string removereceptionist {
                                get {
                                    return ResourceManager.GetString("removereceptionist", resourceCulture);
                                }
                            }
                            
public static string removereservation {
                                get {
                                    return ResourceManager.GetString("removereservation", resourceCulture);
                                }
                            }
                            
public static string removeroom {
                                get {
                                    return ResourceManager.GetString("removeroom", resourceCulture);
                                }
                            }
                            
public static string reputationmanagement {
                                get {
                                    return ResourceManager.GetString("reputationmanagement", resourceCulture);
                                }
                            }
                            
public static string reservation {
                                get {
                                    return ResourceManager.GetString("reservation", resourceCulture);
                                }
                            }
                            
public static string reservation_bookingdate {
                                get {
                                    return ResourceManager.GetString("reservation_bookingdate", resourceCulture);
                                }
                            }
                            
public static string reservation_checkindate {
                                get {
                                    return ResourceManager.GetString("reservation_checkindate", resourceCulture);
                                }
                            }
                            
public static string reservation_checkoutdate {
                                get {
                                    return ResourceManager.GetString("reservation_checkoutdate", resourceCulture);
                                }
                            }
                            
public static string reservation_guestno {
                                get {
                                    return ResourceManager.GetString("reservation_guestno", resourceCulture);
                                }
                            }
                            
public static string reservation_noofguests {
                                get {
                                    return ResourceManager.GetString("reservation_noofguests", resourceCulture);
                                }
                            }
                            
public static string reservation_reservationno {
                                get {
                                    return ResourceManager.GetString("reservation_reservationno", resourceCulture);
                                }
                            }
                            
public static string reservation_reservationstatus {
                                get {
                                    return ResourceManager.GetString("reservation_reservationstatus", resourceCulture);
                                }
                            }
                            
public static string reservation_roomtype {
                                get {
                                    return ResourceManager.GetString("reservation_roomtype", resourceCulture);
                                }
                            }
                            
public static string reservationhandling {
                                get {
                                    return ResourceManager.GetString("reservationhandling", resourceCulture);
                                }
                            }
                            
public static string reservationlist {
                                get {
                                    return ResourceManager.GetString("reservationlist", resourceCulture);
                                }
                            }
                            
public static string roles {
                                get {
                                    return ResourceManager.GetString("roles", resourceCulture);
                                }
                            }
                            
public static string roles_parentname {
                                get {
                                    return ResourceManager.GetString("roles_parentname", resourceCulture);
                                }
                            }
                            
public static string roles_rolegroupname {
                                get {
                                    return ResourceManager.GetString("roles_rolegroupname", resourceCulture);
                                }
                            }
                            
public static string roles_rolehierarchynumber {
                                get {
                                    return ResourceManager.GetString("roles_rolehierarchynumber", resourceCulture);
                                }
                            }
                            
public static string roles_rolename {
                                get {
                                    return ResourceManager.GetString("roles_rolename", resourceCulture);
                                }
                            }
                            
public static string room {
                                get {
                                    return ResourceManager.GetString("room", resourceCulture);
                                }
                            }
                            
public static string room_availablestauts {
                                get {
                                    return ResourceManager.GetString("room_availablestauts", resourceCulture);
                                }
                            }
                            
public static string room_bedtype {
                                get {
                                    return ResourceManager.GetString("room_bedtype", resourceCulture);
                                }
                            }
                            
public static string room_capacitymaxnoofpersons {
                                get {
                                    return ResourceManager.GetString("room_capacitymaxnoofpersons", resourceCulture);
                                }
                            }
                            
public static string room_floornumber {
                                get {
                                    return ResourceManager.GetString("room_floornumber", resourceCulture);
                                }
                            }
                            
public static string room_noofguests {
                                get {
                                    return ResourceManager.GetString("room_noofguests", resourceCulture);
                                }
                            }
                            
public static string room_pricepernight {
                                get {
                                    return ResourceManager.GetString("room_pricepernight", resourceCulture);
                                }
                            }
                            
public static string room_roomno {
                                get {
                                    return ResourceManager.GetString("room_roomno", resourceCulture);
                                }
                            }
                            
public static string room_roomtype {
                                get {
                                    return ResourceManager.GetString("room_roomtype", resourceCulture);
                                }
                            }
                            
public static string roomassignmentallocation {
                                get {
                                    return ResourceManager.GetString("roomassignmentallocation", resourceCulture);
                                }
                            }
                            
public static string roomlist {
                                get {
                                    return ResourceManager.GetString("roomlist", resourceCulture);
                                }
                            }
                            
public static string roomstatusmanagement {
                                get {
                                    return ResourceManager.GetString("roomstatusmanagement", resourceCulture);
                                }
                            }
                            
public static string @save {
                                get {
                                    return ResourceManager.GetString("save", resourceCulture);
                                }
                            }
                            
public static string savedraft {
                                get {
                                    return ResourceManager.GetString("savedraft", resourceCulture);
                                }
                            }
                            
public static string settings {
                                get {
                                    return ResourceManager.GetString("settings", resourceCulture);
                                }
                            }
                            
public static string setuptechnicalpreparation {
                                get {
                                    return ResourceManager.GetString("setuptechnicalpreparation", resourceCulture);
                                }
                            }
                            
public static string setuphotelowners {
                                get {
                                    return ResourceManager.GetString("setuphotelowners", resourceCulture);
                                }
                            }
                            
public static string setuphotelownersusers {
                                get {
                                    return ResourceManager.GetString("setuphotelownersusers", resourceCulture);
                                }
                            }
                            
public static string stockcontrolreorderexecution {
                                get {
                                    return ResourceManager.GetString("stockcontrolreorderexecution", resourceCulture);
                                }
                            }
                            
public static string submit {
                                get {
                                    return ResourceManager.GetString("submit", resourceCulture);
                                }
                            }
                            
public static string suspendprofile {
                                get {
                                    return ResourceManager.GetString("suspendprofile", resourceCulture);
                                }
                            }
                            
public static string tenant {
                                get {
                                    return ResourceManager.GetString("tenant", resourceCulture);
                                }
                            }
                            
public static string tenant_addressline1 {
                                get {
                                    return ResourceManager.GetString("tenant_addressline1", resourceCulture);
                                }
                            }
                            
public static string tenant_addressline2 {
                                get {
                                    return ResourceManager.GetString("tenant_addressline2", resourceCulture);
                                }
                            }
                            
public static string tenant_businessemail {
                                get {
                                    return ResourceManager.GetString("tenant_businessemail", resourceCulture);
                                }
                            }
                            
public static string tenant_businessname {
                                get {
                                    return ResourceManager.GetString("tenant_businessname", resourceCulture);
                                }
                            }
                            
public static string tenant_businessphone {
                                get {
                                    return ResourceManager.GetString("tenant_businessphone", resourceCulture);
                                }
                            }
                            
public static string tenant_businesswebsite {
                                get {
                                    return ResourceManager.GetString("tenant_businesswebsite", resourceCulture);
                                }
                            }
                            
public static string tenant_city {
                                get {
                                    return ResourceManager.GetString("tenant_city", resourceCulture);
                                }
                            }
                            
public static string tenant_country {
                                get {
                                    return ResourceManager.GetString("tenant_country", resourceCulture);
                                }
                            }
                            
public static string tenant_natureofbusiness {
                                get {
                                    return ResourceManager.GetString("tenant_natureofbusiness", resourceCulture);
                                }
                            }
                            
public static string tenant_numberofemployees {
                                get {
                                    return ResourceManager.GetString("tenant_numberofemployees", resourceCulture);
                                }
                            }
                            
public static string tenant_organizationlogo {
                                get {
                                    return ResourceManager.GetString("tenant_organizationlogo", resourceCulture);
                                }
                            }
                            
public static string tenant_parentid {
                                get {
                                    return ResourceManager.GetString("tenant_parentid", resourceCulture);
                                }
                            }
                            
public static string tenant_password {
                                get {
                                    return ResourceManager.GetString("tenant_password", resourceCulture);
                                }
                            }
                            
public static string tenant_statename {
                                get {
                                    return ResourceManager.GetString("tenant_statename", resourceCulture);
                                }
                            }
                            
public static string tenant_username {
                                get {
                                    return ResourceManager.GetString("tenant_username", resourceCulture);
                                }
                            }
                            
public static string tenant_userrole {
                                get {
                                    return ResourceManager.GetString("tenant_userrole", resourceCulture);
                                }
                            }
                            
public static string tenant_zip {
                                get {
                                    return ResourceManager.GetString("tenant_zip", resourceCulture);
                                }
                            }
                            
public static string tenantdisplayname {
                                get {
                                    return ResourceManager.GetString("tenantdisplayname", resourceCulture);
                                }
                            }
                            
public static string @to {
                                get {
                                    return ResourceManager.GetString("to", resourceCulture);
                                }
                            }
                            
public static string trainingcertificationmanagement {
                                get {
                                    return ResourceManager.GetString("trainingcertificationmanagement", resourceCulture);
                                }
                            }
                            
public static string updatealerttemplates {
                                get {
                                    return ResourceManager.GetString("updatealerttemplates", resourceCulture);
                                }
                            }
                            
public static string updatecheckin {
                                get {
                                    return ResourceManager.GetString("updatecheckin", resourceCulture);
                                }
                            }
                            
public static string updatecheckout {
                                get {
                                    return ResourceManager.GetString("updatecheckout", resourceCulture);
                                }
                            }
                            
public static string updatefeedback {
                                get {
                                    return ResourceManager.GetString("updatefeedback", resourceCulture);
                                }
                            }
                            
public static string updateguest {
                                get {
                                    return ResourceManager.GetString("updateguest", resourceCulture);
                                }
                            }
                            
public static string updatehotelowners {
                                get {
                                    return ResourceManager.GetString("updatehotelowners", resourceCulture);
                                }
                            }
                            
public static string updatehousekeeping {
                                get {
                                    return ResourceManager.GetString("updatehousekeeping", resourceCulture);
                                }
                            }
                            
public static string updateinvoice {
                                get {
                                    return ResourceManager.GetString("updateinvoice", resourceCulture);
                                }
                            }
                            
public static string updatemaillog {
                                get {
                                    return ResourceManager.GetString("updatemaillog", resourceCulture);
                                }
                            }
                            
public static string updatepayment {
                                get {
                                    return ResourceManager.GetString("updatepayment", resourceCulture);
                                }
                            }
                            
public static string updateprofile {
                                get {
                                    return ResourceManager.GetString("updateprofile", resourceCulture);
                                }
                            }
                            
public static string updatereceptionist {
                                get {
                                    return ResourceManager.GetString("updatereceptionist", resourceCulture);
                                }
                            }
                            
public static string updatereservation {
                                get {
                                    return ResourceManager.GetString("updatereservation", resourceCulture);
                                }
                            }
                            
public static string updateroom {
                                get {
                                    return ResourceManager.GetString("updateroom", resourceCulture);
                                }
                            }
                            
public static string user {
                                get {
                                    return ResourceManager.GetString("user", resourceCulture);
                                }
                            }
                            
public static string users {
                                get {
                                    return ResourceManager.GetString("users", resourceCulture);
                                }
                            }
                            
public static string users_emailid {
                                get {
                                    return ResourceManager.GetString("users_emailid", resourceCulture);
                                }
                            }
                            
public static string users_firstname {
                                get {
                                    return ResourceManager.GetString("users_firstname", resourceCulture);
                                }
                            }
                            
public static string users_lastname {
                                get {
                                    return ResourceManager.GetString("users_lastname", resourceCulture);
                                }
                            }
                            
public static string users_mobilenumber {
                                get {
                                    return ResourceManager.GetString("users_mobilenumber", resourceCulture);
                                }
                            }
                            
public static string users_passwordkey {
                                get {
                                    return ResourceManager.GetString("users_passwordkey", resourceCulture);
                                }
                            }
                            
public static string users_profilepicture {
                                get {
                                    return ResourceManager.GetString("users_profilepicture", resourceCulture);
                                }
                            }
                            
public static string users_username {
                                get {
                                    return ResourceManager.GetString("users_username", resourceCulture);
                                }
                            }
                            
public static string users_userpassword {
                                get {
                                    return ResourceManager.GetString("users_userpassword", resourceCulture);
                                }
                            }
                            
public static string users_userrole {
                                get {
                                    return ResourceManager.GetString("users_userrole", resourceCulture);
                                }
                            }
                            
public static string viewdetailshotelowners {
                                get {
                                    return ResourceManager.GetString("viewdetailshotelowners", resourceCulture);
                                }
                            }
                            
public static string viewdraft {
                                get {
                                    return ResourceManager.GetString("viewdraft", resourceCulture);
                                }
                            }
                            
public static string viewdraftlist {
                                get {
                                    return ResourceManager.GetString("viewdraftlist", resourceCulture);
                                }
                            }
                            
public static string viewlistofhotelowners {
                                get {
                                    return ResourceManager.GetString("viewlistofhotelowners", resourceCulture);
                                }
                            }
                            
public static string workforcescheduling {
                                get {
                                    return ResourceManager.GetString("workforcescheduling", resourceCulture);
                                }
                            }
                            
public static string workordermanagement {
                                get {
                                    return ResourceManager.GetString("workordermanagement", resourceCulture);
                                }
                            }
                            

    }
}

